name: Continue General Review

on:
  pull_request:
    types: [opened, ready_for_review]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  general-code-review:
    name: Continue General Review
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Run Continue PR Review Action
        uses: continuedev/continue/actions/general-review@b3f4b82600f603ca28c65a319b80ec36c4644ed7
        with:
          continue-api-key: ${{ secrets.CONTINUE_API_KEY }}
          continue-org: "continuedev"
          continue-config: "continuedev/review-bot"
